# global.R
library(shiny)
library(shinySignals)   
library(dplyr)
library(shinydashboard)
library(bubbles)        
library(fireData)
library(jsonlite)
library(httr)
library(plotly)
# source("bloomfilter.R")